switcher_space = hs.window.switcher.new(hs.window.filter.new():setCurrentSpace(true):setDefaultFilter({}))
hs.hotkey.bind("ctrl-alt-cmd", "j", "Next window", function()
	switcher_space:next()
end)
hs.hotkey.bind("ctrl-alt-cmd", "k", "Previous window", function()
	switcher_space:previous()
end)
hs.hotkey.bind("ctrl-alt-cmd", "return", "Maximize current window", function()
	hs.window.focusedWindow():maximize()
end)
hs.hotkey.bind("ctrl-alt-cmd", "h", "Move current one screen west", function()
	hs.window.focusedWindow():moveOneScreenWest()
end)
hs.hotkey.bind("ctrl-alt-cmd", "l", "Move current one screen east", function()
	hs.window.focusedWindow():moveOneScreenEast()
end)
